fail_fast: true
default_install_hook_types: [pre-push]
exclude: |
  (?x)^(
    .*/(snapshots)/.*|
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        exclude: .*/examine.*\.txt
      - id: end-of-file-fixer

  - repo: https://github.com/crate-ci/typos
    rev: v1.39.2
    hooks:
      - id: typos
